name: Integration Tests
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
   integration-tests:
    runs-on: ubuntu-latest
    name: Integration Tests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests using Docker
        run: ./compose-test.sh
